import Head from "next/head";
import { Inter } from "next/font/google";
import ReadingList from "@/components/ReadingList";
import AddBook from "@/components/AddBook";
import { readingList } from "@/constants";
import { useState } from "react";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  const [cardArray, setCardArray] = useState(readingList);
  const [id, setId] = useState(4);
  const [newBook, setNewBook] = useState("");
  const [inputText, setInputText] = useState("");

  function handleOnChange(e) {
    setInputText(e.target.value);
    setNewBook(e.target.value);
  };

  function pushNewBookCard() {
    setId(id + 1);
    console.log(id);
    setCardArray(
      readingList.push({
        id: id,
        title: newBook,
        author: "David Guterson",
        imgUrl:
          "https://books.google.com/books/content?id=1m-rnhIW-iAC&pg=PP1&img=1&zoom=3&hl=en&bul=1&sig=ACfU3U3g_-YUiF7S3c6IrngPZFqjFvzbUg&w=1280",
        description:
          "Set on the fictional San Piedro Island in the Strait of Juan de Fuca, just north of Puget Sound, in the state of Washington in 1954, the plot revolves around a murder case in which Kabuo Miyamoto, a Japanese American, is accused of killing Carl Heine, a respected fisherman in the close-knit community.",
      })
    );
    console.log(readingList);
  }

  function handleOnSubmit(e) {
    e.preventDefault();
    pushNewBookCard();
    setInputText("");
  }

  return (
    <>
      <Head>
        <title>Reading List</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        {/* Reading List */}
        <ReadingList readingList={readingList} />
        {/* Add Book */}
        <AddBook
          onSubmit={handleOnSubmit}
          setNewBook={setNewBook}
          onChange={handleOnChange}
          inputText={inputText}
        />
      </main>
    </>
  );
}
